/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/Path.gltf -t -r public 
*/

import * as THREE from 'three'
import { Float, useGLTF, useScroll } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JSX } from 'react'
import scrollOffsets from '@/domain/constants/scrollOffsets'

type GLTFResult = GLTF & {
  nodes: {
    United_Path: THREE.Mesh
    ['1-Letters']: THREE.Mesh
    ['2-Profile']: THREE.Mesh
    ['3-Computer']: THREE.Mesh
    ['3-ComputerScreen']: THREE.Mesh
    ['3-ComputerScreenLetters']: THREE.Mesh
    ['4-Avanade1']: THREE.Mesh
    ['4-Avanade2']: THREE.Mesh
    ['4-Avanade3']: THREE.Mesh
    ['4-Avanade4']: THREE.Mesh
    ['5-RumoLogo']: THREE.Mesh
    ['6-MouseCursor']: THREE.Mesh
    ['7-GraduationHat']: THREE.Mesh
    ['7-GraduationHatThing']: THREE.Mesh
    ['8-Link']: THREE.Mesh
  }
}

const iconsStandardMaterialsConfig = {
  roughness: 0.1
}

export default function Path(props: JSX.IntrinsicElements['group']) {
  const scroll = useScroll()

  const { nodes } = useGLTF('/3d/Path.gltf') as unknown as GLTFResult

  function scrollToSection(scrollOffset: number){
    const targetPixel = (scroll.el.scrollHeight - window.innerHeight) * (scrollOffset + 0.01)

    scroll.el.scrollTo({
      behavior: 'smooth',
      top: targetPixel
    })
  }

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.United_Path.geometry}>
        <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#ffe7cc'/>
      </mesh>

      <Float floatIntensity={1.5} floatingRange={[0, 2]} rotationIntensity={0.1} speed={2}>        
        <mesh geometry={nodes['1-Letters'].geometry} onClick={() => scrollToSection(scrollOffsets.introduction)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#ffa033'/>
        </mesh>
        <mesh geometry={nodes['2-Profile'].geometry} onClick={() => scrollToSection(scrollOffsets.about)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#b2fcff'/>
        </mesh>
        <mesh geometry={nodes['3-Computer'].geometry} onClick={() => scrollToSection(scrollOffsets.experience)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#0d0d0d'/>
        </mesh>
        <mesh geometry={nodes['3-ComputerScreen'].geometry} onClick={() => scrollToSection(scrollOffsets.experience)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#808080'/>
        </mesh>
        <mesh geometry={nodes['3-ComputerScreenLetters'].geometry} onClick={() => scrollToSection(scrollOffsets.experience)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#e5e5e5'/>
        </mesh>
        <mesh geometry={nodes['4-Avanade1'].geometry} onClick={() => scrollToSection(scrollOffsets.experience1)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#c80000'/>
        </mesh>
        <mesh geometry={nodes['4-Avanade2'].geometry} onClick={() => scrollToSection(scrollOffsets.experience1)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#ff5800'/>
        </mesh>
        <mesh geometry={nodes['4-Avanade3'].geometry} onClick={() => scrollToSection(scrollOffsets.experience1)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#ff5800'/>
        </mesh>
        <mesh geometry={nodes['4-Avanade4'].geometry} onClick={() => scrollToSection(scrollOffsets.experience1)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#ffb414'/>
        </mesh>
        <mesh geometry={nodes['5-RumoLogo'].geometry} onClick={() => scrollToSection(scrollOffsets.experience2)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#0fe8f9'/>
        </mesh>
        <mesh geometry={nodes['6-MouseCursor'].geometry} onClick={() => scrollToSection(scrollOffsets.experience3)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#ccb9a3'/>
        </mesh>
        <mesh geometry={nodes['7-GraduationHat'].geometry} onClick={() => scrollToSection(scrollOffsets.education)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#002780'/>
        </mesh>
        <mesh geometry={nodes['7-GraduationHatThing'].geometry} onClick={() => scrollToSection(scrollOffsets.education)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#805d00'/>
        </mesh>
        <mesh geometry={nodes['8-Link'].geometry} onClick={() => scrollToSection(scrollOffsets.links)}>
          <meshStandardMaterial {...iconsStandardMaterialsConfig} color='#cc0000'/>
        </mesh>
      </Float>
    </group>
  )
}

useGLTF.preload('/3d/Path.gltf')
