/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/assets/3d/Path.gltf -t -r public
*/

import * as THREE from 'three'
import { Float, useGLTF, useScroll } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { sectionsScrollOffsets, sphereRotations } from '../../../common/globalConstants'

type GLTFResult = GLTF & {
  nodes: {
    United_Path: THREE.Mesh
    ['1-Letters']: THREE.Mesh
    ['2-Profile']: THREE.Mesh
    ['3-Computer']: THREE.Mesh
    ['3-ComputerScreen']: THREE.Mesh
    ['3-ComputerScreenLetters']: THREE.Mesh
    ['4-Headphone']: THREE.Mesh
    ['4-HeadphonesEars']: THREE.Mesh
    ['5-SoccerBallBlack']: THREE.Mesh
    ['5-SoccerBallWhite']: THREE.Mesh
    ['6-Hourglass']: THREE.Mesh
    ['6-HourglassBase']: THREE.Mesh
    ['7-GraduationHat']: THREE.Mesh
    ['7-GraduationHatThing']: THREE.Mesh
    ['8-Link']: THREE.Mesh
  }
  materials: {}
}

const iconsStandardMaterialsConfig = {
  metalness: 1,
  roughness: 0.5
}

export default function Path(props: JSX.IntrinsicElements['group']) {
  const scroll = useScroll()

  const group = useRef<THREE.Group>(null)

  const offsetsKeys = Object.keys(sectionsScrollOffsets)
  const rotationsKeys = Object.keys(sphereRotations)

  useFrame(()=>{
    if (scroll.offset <= sectionsScrollOffsets.introduction && group.current) {
      group.current.rotation.z = 0
      return
    }
    
    offsetsKeys.forEach((key, index) => {
      const previousOffset = sectionsScrollOffsets[offsetsKeys[index - 1]]
      const previousRotation = sphereRotations[rotationsKeys[index - 1]]

      if (index > 0 && scroll.offset <= sectionsScrollOffsets[key] && scroll.offset > previousOffset && group.current) {
        let offsetDifference = previousOffset - sectionsScrollOffsets[key]
        let rotationDifference = sphereRotations[key] - previousRotation

        if (offsetDifference < 0) {
          offsetDifference *= -1
        }

        const newPathZRotation =
        previousRotation
        + rotationDifference
        * scroll.range(previousOffset, offsetDifference)

        group.current.rotation.z = newPathZRotation
      }
    })
  })

  const { nodes, materials } = useGLTF('/assets/3d/Path.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} ref={group}>
      <mesh geometry={nodes.United_Path.geometry} rotation={[-1.2, 0.68, -0.55]} scale={[0.06, 0.16, 0.2]} >
        <meshStandardMaterial color='#ffe7cc' roughness={0.1} />
      </mesh>

      <Float floatingRange={[0, 2]} floatIntensity={1.5} rotationIntensity={0.1} speed={2}>
        <mesh geometry={nodes['1-Letters'].geometry} scale={[10, 10, 2]} >
          <meshStandardMaterial color='#ccc' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['2-Profile'].geometry} rotation={[0.7, 0, -0.52]} scale={[6, 10, 4]} >
          <meshStandardMaterial color='#b2fcff' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['3-Computer'].geometry} rotation={[1.4, 0, 0]} scale={[16, 9.6, 1.6]} >
          <meshStandardMaterial color='#0d0d0d' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['3-ComputerScreen'].geometry} rotation={[1.4, 0, 0]} scale={[16, 9.6, 1.6]} >
          <meshStandardMaterial color='#808080' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['3-ComputerScreenLetters'].geometry} rotation={[1.4, 0, 0]} scale={[1.68, 4.2, 1.68]} >
          <meshStandardMaterial color='#e5e5e5' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['4-Headphone'].geometry} rotation={[2.08, 0.01, -1.11]} scale={[7, 1.4, 7]} >
          <meshStandardMaterial color='#5D3FD3' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['4-HeadphonesEars'].geometry} rotation={[2.08, 0.01, -1.11]} scale={[7, 1.4, 7]} >
          <meshStandardMaterial color='#222126' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['5-SoccerBallBlack'].geometry} rotation={[1.51, 0.82, 2.8]} scale={11.01} position={[0, -0.2, 0]}>
          <meshStandardMaterial color='#1a1a1a' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['5-SoccerBallWhite'].geometry} rotation={[1.51, 0.82, 2.8]} scale={10.84} >
          <meshStandardMaterial color='#e5e5e5' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['6-Hourglass'].geometry} rotation={[-2.71, 0, 0.47]} scale={10} >
          <meshStandardMaterial color='#ccb499' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['6-HourglassBase'].geometry} rotation={[-2.71, 0, 0.47]} scale={10} >
          <meshStandardMaterial color='#806240' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['7-GraduationHat'].geometry} rotation={[-2.09, -0.3, 0]} scale={[10, 4, 10]} >
          <meshStandardMaterial color='#002780' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['7-GraduationHatThing'].geometry} rotation={[-2.09, 0.32, 0]} scale={[0.8, 10, 0.8]} >
          <meshStandardMaterial color='#805d00' {...iconsStandardMaterialsConfig} />
        </mesh>

        <mesh geometry={nodes['8-Link'].geometry} rotation={[-0.27, -1.35, -0.6]} scale={5} >
          <meshStandardMaterial color='#cc0000' {...iconsStandardMaterialsConfig} />
        </mesh>
      </Float>
    </group>
  )
}

useGLTF.preload('/assets/3d/Path.gltf')
