/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/Sphere.gltf -t -r public 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Sphere001: THREE.Mesh
  }
}

export default function Sphere(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/3d/Sphere.gltf') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001.geometry}>
        <meshStandardMaterial color='#ff9316' metalness={1} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/3d/Sphere.gltf')
