/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/assets/3d/Sphere.gltf -t -r public
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere001: THREE.Mesh
  }
  materials: {}
}

export default function Sphere(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/3d/Sphere.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material}>
        <meshStandardMaterial color='#ff9316' metalness={1}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/assets/3d/Sphere.gltf')
