/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/Letters.gltf -t -r public 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
	nodes: {
		United_Letters: THREE.Mesh
	}
}

export default function Model() {
	const { nodes } = useGLTF('/3d/Letters.gltf') as unknown as GLTFResult

	return (
		<group dispose={null} scale={40}>
			<mesh geometry={nodes.United_Letters.geometry}>
				<meshStandardMaterial color='#ff9316' roughness={0.1} />
			</mesh>
		</group>
	)
}

useGLTF.preload('/3d/Letters.gltf')
